version: '3.3'
services:
  k2fs:
    image: kiyor/k2fs
    container_name: k2fs
    command:
      - "su-exec"
      - "110:110"
      - "/bin/k2fs"
      - "-root"
      - "/mnt/disk/folder"
      - "-l"
      - ":8080"
      - "-cache-timeout"
      - "10m"
      - "-cache-max"
      - "5000"
      - "-host"
      - "http://192.168.10.10"
    volumes:
      - "/mnt/disk/folder:/mnt/disk/folder"
    ports:
      - 8080:8080
    restart: always
