FROM alpine
RUN apk update && apk add ca-certificates su-exec tzdata && rm -rf /var/cache/apk/*
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
WORKDIR /bin
COPY k2fs .
EXPOSE 8080
CMD ["./k2fs"]
